---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "kubernetes-cluster-chart.cluster.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    enabled: true
    port: 6443
    region: {{ .Values.hetzner.region | default "nbg1"  | quote }}
  controlPlaneRegions:
    - {{ .Values.hetzner.region | default "nbg1"  | quote }}
  hcloudNetwork:
    enabled: false
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    - name: worker-plane
      type: spread
  hetznerSecretRef:
    key:
      hcloudToken: token
    name: hcloud
  sshKeys:
    hcloud:
      - name: christian.huth@cloud37.io
      - name: florian.wartner@cloud37.io
      - name: kenneth@kenneth-cloud37-hp
