---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "hetznernetes.cluster.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    enabled: true
    port: 6443
    region: {{ .Values.hetzner.region | default "nbg1"  | quote }}
  controlPlaneRegions:
    - {{ .Values.hetzner.region | default "nbg1"  | quote }}
  hcloudNetwork:
    enabled: false
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    - name: worker-plane
      type: spread
  hetznerSecretRef:
    key:
      hcloudToken: token
    name: hcloud
  {{- if .Values.hetzner.sshKeys.hcloud }}
  sshKeys:
    hcloud:
      {{- .Values.hetzner.sshKeys.hcloud | toYaml | nindent 6 }}
  {{- end }}
