---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "kubernetes-cluster-chart.worker-plane.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      imageName: {{ .Values.hetzner.workerPlane.imageName | quote }}
      placementGroupName: worker-plane
      type: {{ .Values.hetzner.workerPlane.serverType | quote }}
