---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: {{ include "hetznernetes.worker-plane.name" . }}
  name: {{ include "hetznernetes.worker-plane.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ include "hetznernetes.cluster.name" . }}
  replicas: {{ .Values.kubernetes.workerPlane.replicas }}
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        nodepool: {{ include "hetznernetes.worker-plane.name" . }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "hetznernetes.worker-plane.name" . }}
      clusterName: {{ include "hetznernetes.cluster.name" . }}
      failureDomain: {{ .Values.hetzner.region | quote }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ include "hetznernetes.worker-plane.name" . }}
      version: {{ .Values.kubernetes.version }}
