---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "hetznernetes.worker-plane.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ include "hetznernetes.cluster.name" . }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 10m
  remediationTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    name: {{ include "hetznernetes.worker-plane.name" . }}
  selector:
    matchLabels:
      nodepool: {{ include "hetznernetes.worker-plane.name" . }}
  unhealthyConditions:
    - status: Unknown
      timeout: 180s
      type: Ready
    - status: "False"
      timeout: 180s
      type: Ready
