---
# -- Provide a name in place of `hetznernetes`
nameOverride: ""

# -- String to fully override `"hetznernetes.fullname"`
fullnameOverride: ""

cluster:
  # -- Define the name of the cluster. If not set, `"hetznernetes.fullname"` will be used.
  name: ""

containerd:
  # -- The containerd version that should be used in the form MAJOR.MINOR.PATH without a leading "v".
  version: "1.7.17"

kubernetes:
  controlPlane:
    # -- How many control-planes should be running
    replicas: 3
  # -- The Kubernetes version that should be used in the form MAJOR.MINOR.PATH without a leading "v".
  version: "1.31.0"
  workerPlane:
    # -- How many worker-planes should be running
    replicas: 3

hetzner:
  controlPlane:
    # -- image that should be used to install the control plane
    imageName: "ubuntu-22.04"
    # -- server type that should be used for the control plane
    serverType: "cpx21"
  # -- contains the name of the HCloud location where all components (VMs, LoadBalancer) will be running. Valid values: fsn1, hel1, nbg1, ash, hil.
  region: "nbg1"
  sshKeys:
    # example
    # hcloud:
    #   - name: christian.huth@cloud37.io
    #   - name: florian.wartner@cloud37.io
    #   - name: kenneth@kenneth-cloud37-hp
    # -- Defines the SSH keys used for hcloud.
    hcloud: []
  workerPlane:
    # -- image that should be used to install the control plane
    imageName: "ubuntu-22.04"
    # -- server type that should be used for the control plane
    serverType: "cpx31"
