---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hetznernetes.control-plane.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      imageName: {{ .Values.hetzner.controlPlane.imageName | quote }}
      placementGroupName: control-plane
      type: {{ .Values.hetzner.controlPlane.serverType | quote }}
